; LightPodcast config
; Add one RSS feed URL per line under [feeds]
[settings]
sort=date:asc
w1=203
w2=451
vol=100

[feeds]
https://feeds.megaphone.fm/wolf359radio
https://feeds.megaphone.fm/GLSS8724189069
