; LightPodcast config
; Add one RSS feed URL per line under [feeds]
[settings]
sort=date:asc
w1=252
w2=400
cw0=84
cw1=101
cw2=46
vol=100
font=0
winw=734
winh=510
cachedir=C:\Users\15923\Desktop\lightpodcast\cache

[feeds]
https://feeds.megaphone.fm/wolf359radio
https://feeds.megaphone.fm/GLSS8724189069
