; LightPodcast config
; Add one RSS feed URL per line under [feeds]
[settings]
sort=title:asc
w1=260
w2=400
cw0=300
cw1=122
cw2=64
vol=80
font=0
winw=480
winh=360

[feeds]
https://feeds.megaphone.fm/wolf359radio
